<?php
/**
 * APIMATERIALSTOCKSRVAMatlStkInAcctModTypeUpdate
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\MaterialStock
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Material Stock - Read
 *
 * This service enables you to retrieve material stock information using the OData protocol with filter data provided in the payload. It can be consumed by external warehouse applications.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BeLenka\SAP\MaterialStock\Model;

use \ArrayAccess;
use \BeLenka\SAP\MaterialStock\ObjectSerializer;

/**
 * APIMATERIALSTOCKSRVAMatlStkInAcctModTypeUpdate Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\MaterialStock
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class APIMATERIALSTOCKSRVAMatlStkInAcctModTypeUpdate implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'API_MATERIAL_STOCK_SRV.A_MatlStkInAcctModType-update';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'wbs_element_external_id' => 'string',
        'material_base_unit' => 'string',
        'matl_wrhs_stk_qty_in_matl_base_unit' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'wbs_element_external_id' => null,
        'material_base_unit' => null,
        'matl_wrhs_stk_qty_in_matl_base_unit' => 'decimal'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'wbs_element_external_id' => true,
		'material_base_unit' => true,
		'matl_wrhs_stk_qty_in_matl_base_unit' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'wbs_element_external_id' => 'WBSElementExternalID',
        'material_base_unit' => 'MaterialBaseUnit',
        'matl_wrhs_stk_qty_in_matl_base_unit' => 'MatlWrhsStkQtyInMatlBaseUnit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'wbs_element_external_id' => 'setWbsElementExternalId',
        'material_base_unit' => 'setMaterialBaseUnit',
        'matl_wrhs_stk_qty_in_matl_base_unit' => 'setMatlWrhsStkQtyInMatlBaseUnit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'wbs_element_external_id' => 'getWbsElementExternalId',
        'material_base_unit' => 'getMaterialBaseUnit',
        'matl_wrhs_stk_qty_in_matl_base_unit' => 'getMatlWrhsStkQtyInMatlBaseUnit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('wbs_element_external_id', $data ?? [], null);
        $this->setIfExists('material_base_unit', $data ?? [], null);
        $this->setIfExists('matl_wrhs_stk_qty_in_matl_base_unit', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['wbs_element_external_id']) && (mb_strlen($this->container['wbs_element_external_id']) > 24)) {
            $invalidProperties[] = "invalid value for 'wbs_element_external_id', the character length must be smaller than or equal to 24.";
        }

        if (!is_null($this->container['material_base_unit']) && (mb_strlen($this->container['material_base_unit']) > 3)) {
            $invalidProperties[] = "invalid value for 'material_base_unit', the character length must be smaller than or equal to 3.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets wbs_element_external_id
     *
     * @return string|null
     */
    public function getWbsElementExternalId()
    {
        return $this->container['wbs_element_external_id'];
    }

    /**
     * Sets wbs_element_external_id
     *
     * @param string|null $wbs_element_external_id Work Breakdown Structure Element (WBS Element) Edited
     *
     * @return self
     */
    public function setWbsElementExternalId($wbs_element_external_id)
    {
        if (is_null($wbs_element_external_id)) {
            array_push($this->openAPINullablesSetToNull, 'wbs_element_external_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('wbs_element_external_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($wbs_element_external_id) && (mb_strlen($wbs_element_external_id) > 24)) {
            throw new \InvalidArgumentException('invalid length for $wbs_element_external_id when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeUpdate., must be smaller than or equal to 24.');
        }

        $this->container['wbs_element_external_id'] = $wbs_element_external_id;

        return $this;
    }

    /**
     * Gets material_base_unit
     *
     * @return string|null
     */
    public function getMaterialBaseUnit()
    {
        return $this->container['material_base_unit'];
    }

    /**
     * Sets material_base_unit
     *
     * @param string|null $material_base_unit material_base_unit
     *
     * @return self
     */
    public function setMaterialBaseUnit($material_base_unit)
    {
        if (is_null($material_base_unit)) {
            array_push($this->openAPINullablesSetToNull, 'material_base_unit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('material_base_unit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($material_base_unit) && (mb_strlen($material_base_unit) > 3)) {
            throw new \InvalidArgumentException('invalid length for $material_base_unit when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeUpdate., must be smaller than or equal to 3.');
        }

        $this->container['material_base_unit'] = $material_base_unit;

        return $this;
    }

    /**
     * Gets matl_wrhs_stk_qty_in_matl_base_unit
     *
     * @return float|null
     */
    public function getMatlWrhsStkQtyInMatlBaseUnit()
    {
        return $this->container['matl_wrhs_stk_qty_in_matl_base_unit'];
    }

    /**
     * Sets matl_wrhs_stk_qty_in_matl_base_unit
     *
     * @param float|null $matl_wrhs_stk_qty_in_matl_base_unit matl_wrhs_stk_qty_in_matl_base_unit
     *
     * @return self
     */
    public function setMatlWrhsStkQtyInMatlBaseUnit($matl_wrhs_stk_qty_in_matl_base_unit)
    {
        if (is_null($matl_wrhs_stk_qty_in_matl_base_unit)) {
            array_push($this->openAPINullablesSetToNull, 'matl_wrhs_stk_qty_in_matl_base_unit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('matl_wrhs_stk_qty_in_matl_base_unit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }


        $this->container['matl_wrhs_stk_qty_in_matl_base_unit'] = $matl_wrhs_stk_qty_in_matl_base_unit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


