<?php
/**
 * APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\MaterialStock
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Material Stock - Read
 *
 * This service enables you to retrieve material stock information using the OData protocol with filter data provided in the payload. It can be consumed by external warehouse applications.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BeLenka\SAP\MaterialStock\Model;

use \ArrayAccess;
use \BeLenka\SAP\MaterialStock\ObjectSerializer;

/**
 * APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\MaterialStock
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'API_MATERIAL_STOCK_SRV.A_MatlStkInAcctModType-create';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'material' => 'string',
        'plant' => 'string',
        'storage_location' => 'string',
        'batch' => 'string',
        'supplier' => 'string',
        'customer' => 'string',
        'wbs_element_internal_id' => 'string',
        'sd_document' => 'string',
        'sd_document_item' => 'string',
        'inventory_special_stock_type' => 'string',
        'inventory_stock_type' => 'string',
        'wbs_element_external_id' => 'string',
        'material_base_unit' => 'string',
        'matl_wrhs_stk_qty_in_matl_base_unit' => 'float',
        'to_material_serial_number' => '\BeLenka\SAP\MaterialStock\Model\APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreateToMaterialSerialNumber',
        'to_material_stock' => '\BeLenka\SAP\MaterialStock\Model\APIMATERIALSTOCKSRVAMaterialStockTypeCreate'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'material' => null,
        'plant' => null,
        'storage_location' => null,
        'batch' => null,
        'supplier' => null,
        'customer' => null,
        'wbs_element_internal_id' => null,
        'sd_document' => null,
        'sd_document_item' => null,
        'inventory_special_stock_type' => null,
        'inventory_stock_type' => null,
        'wbs_element_external_id' => null,
        'material_base_unit' => null,
        'matl_wrhs_stk_qty_in_matl_base_unit' => 'decimal',
        'to_material_serial_number' => null,
        'to_material_stock' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'material' => false,
		'plant' => false,
		'storage_location' => false,
		'batch' => false,
		'supplier' => false,
		'customer' => false,
		'wbs_element_internal_id' => false,
		'sd_document' => false,
		'sd_document_item' => false,
		'inventory_special_stock_type' => false,
		'inventory_stock_type' => false,
		'wbs_element_external_id' => true,
		'material_base_unit' => true,
		'matl_wrhs_stk_qty_in_matl_base_unit' => true,
		'to_material_serial_number' => false,
		'to_material_stock' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'material' => 'Material',
        'plant' => 'Plant',
        'storage_location' => 'StorageLocation',
        'batch' => 'Batch',
        'supplier' => 'Supplier',
        'customer' => 'Customer',
        'wbs_element_internal_id' => 'WBSElementInternalID',
        'sd_document' => 'SDDocument',
        'sd_document_item' => 'SDDocumentItem',
        'inventory_special_stock_type' => 'InventorySpecialStockType',
        'inventory_stock_type' => 'InventoryStockType',
        'wbs_element_external_id' => 'WBSElementExternalID',
        'material_base_unit' => 'MaterialBaseUnit',
        'matl_wrhs_stk_qty_in_matl_base_unit' => 'MatlWrhsStkQtyInMatlBaseUnit',
        'to_material_serial_number' => 'to_MaterialSerialNumber',
        'to_material_stock' => 'to_MaterialStock'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'material' => 'setMaterial',
        'plant' => 'setPlant',
        'storage_location' => 'setStorageLocation',
        'batch' => 'setBatch',
        'supplier' => 'setSupplier',
        'customer' => 'setCustomer',
        'wbs_element_internal_id' => 'setWbsElementInternalId',
        'sd_document' => 'setSdDocument',
        'sd_document_item' => 'setSdDocumentItem',
        'inventory_special_stock_type' => 'setInventorySpecialStockType',
        'inventory_stock_type' => 'setInventoryStockType',
        'wbs_element_external_id' => 'setWbsElementExternalId',
        'material_base_unit' => 'setMaterialBaseUnit',
        'matl_wrhs_stk_qty_in_matl_base_unit' => 'setMatlWrhsStkQtyInMatlBaseUnit',
        'to_material_serial_number' => 'setToMaterialSerialNumber',
        'to_material_stock' => 'setToMaterialStock'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'material' => 'getMaterial',
        'plant' => 'getPlant',
        'storage_location' => 'getStorageLocation',
        'batch' => 'getBatch',
        'supplier' => 'getSupplier',
        'customer' => 'getCustomer',
        'wbs_element_internal_id' => 'getWbsElementInternalId',
        'sd_document' => 'getSdDocument',
        'sd_document_item' => 'getSdDocumentItem',
        'inventory_special_stock_type' => 'getInventorySpecialStockType',
        'inventory_stock_type' => 'getInventoryStockType',
        'wbs_element_external_id' => 'getWbsElementExternalId',
        'material_base_unit' => 'getMaterialBaseUnit',
        'matl_wrhs_stk_qty_in_matl_base_unit' => 'getMatlWrhsStkQtyInMatlBaseUnit',
        'to_material_serial_number' => 'getToMaterialSerialNumber',
        'to_material_stock' => 'getToMaterialStock'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('material', $data ?? [], null);
        $this->setIfExists('plant', $data ?? [], null);
        $this->setIfExists('storage_location', $data ?? [], null);
        $this->setIfExists('batch', $data ?? [], null);
        $this->setIfExists('supplier', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('wbs_element_internal_id', $data ?? [], null);
        $this->setIfExists('sd_document', $data ?? [], null);
        $this->setIfExists('sd_document_item', $data ?? [], null);
        $this->setIfExists('inventory_special_stock_type', $data ?? [], null);
        $this->setIfExists('inventory_stock_type', $data ?? [], null);
        $this->setIfExists('wbs_element_external_id', $data ?? [], null);
        $this->setIfExists('material_base_unit', $data ?? [], null);
        $this->setIfExists('matl_wrhs_stk_qty_in_matl_base_unit', $data ?? [], null);
        $this->setIfExists('to_material_serial_number', $data ?? [], null);
        $this->setIfExists('to_material_stock', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['material'] === null) {
            $invalidProperties[] = "'material' can't be null";
        }
        if ((mb_strlen($this->container['material']) > 40)) {
            $invalidProperties[] = "invalid value for 'material', the character length must be smaller than or equal to 40.";
        }

        if ($this->container['plant'] === null) {
            $invalidProperties[] = "'plant' can't be null";
        }
        if ((mb_strlen($this->container['plant']) > 4)) {
            $invalidProperties[] = "invalid value for 'plant', the character length must be smaller than or equal to 4.";
        }

        if ($this->container['storage_location'] === null) {
            $invalidProperties[] = "'storage_location' can't be null";
        }
        if ((mb_strlen($this->container['storage_location']) > 4)) {
            $invalidProperties[] = "invalid value for 'storage_location', the character length must be smaller than or equal to 4.";
        }

        if ($this->container['batch'] === null) {
            $invalidProperties[] = "'batch' can't be null";
        }
        if ((mb_strlen($this->container['batch']) > 10)) {
            $invalidProperties[] = "invalid value for 'batch', the character length must be smaller than or equal to 10.";
        }

        if ($this->container['supplier'] === null) {
            $invalidProperties[] = "'supplier' can't be null";
        }
        if ((mb_strlen($this->container['supplier']) > 10)) {
            $invalidProperties[] = "invalid value for 'supplier', the character length must be smaller than or equal to 10.";
        }

        if ($this->container['customer'] === null) {
            $invalidProperties[] = "'customer' can't be null";
        }
        if ((mb_strlen($this->container['customer']) > 10)) {
            $invalidProperties[] = "invalid value for 'customer', the character length must be smaller than or equal to 10.";
        }

        if ($this->container['wbs_element_internal_id'] === null) {
            $invalidProperties[] = "'wbs_element_internal_id' can't be null";
        }
        if ((mb_strlen($this->container['wbs_element_internal_id']) > 8)) {
            $invalidProperties[] = "invalid value for 'wbs_element_internal_id', the character length must be smaller than or equal to 8.";
        }

        if ($this->container['sd_document'] === null) {
            $invalidProperties[] = "'sd_document' can't be null";
        }
        if ((mb_strlen($this->container['sd_document']) > 10)) {
            $invalidProperties[] = "invalid value for 'sd_document', the character length must be smaller than or equal to 10.";
        }

        if ($this->container['sd_document_item'] === null) {
            $invalidProperties[] = "'sd_document_item' can't be null";
        }
        if ((mb_strlen($this->container['sd_document_item']) > 6)) {
            $invalidProperties[] = "invalid value for 'sd_document_item', the character length must be smaller than or equal to 6.";
        }

        if ($this->container['inventory_special_stock_type'] === null) {
            $invalidProperties[] = "'inventory_special_stock_type' can't be null";
        }
        if ((mb_strlen($this->container['inventory_special_stock_type']) > 1)) {
            $invalidProperties[] = "invalid value for 'inventory_special_stock_type', the character length must be smaller than or equal to 1.";
        }

        if ($this->container['inventory_stock_type'] === null) {
            $invalidProperties[] = "'inventory_stock_type' can't be null";
        }
        if ((mb_strlen($this->container['inventory_stock_type']) > 2)) {
            $invalidProperties[] = "invalid value for 'inventory_stock_type', the character length must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['wbs_element_external_id']) && (mb_strlen($this->container['wbs_element_external_id']) > 24)) {
            $invalidProperties[] = "invalid value for 'wbs_element_external_id', the character length must be smaller than or equal to 24.";
        }

        if (!is_null($this->container['material_base_unit']) && (mb_strlen($this->container['material_base_unit']) > 3)) {
            $invalidProperties[] = "invalid value for 'material_base_unit', the character length must be smaller than or equal to 3.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets material
     *
     * @return string
     */
    public function getMaterial()
    {
        return $this->container['material'];
    }

    /**
     * Sets material
     *
     * @param string $material Material in Respect of Which Stock is Managed
     *
     * @return self
     */
    public function setMaterial($material)
    {
        if (is_null($material)) {
            throw new \InvalidArgumentException('non-nullable material cannot be null');
        }
        if ((mb_strlen($material) > 40)) {
            throw new \InvalidArgumentException('invalid length for $material when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 40.');
        }

        $this->container['material'] = $material;

        return $this;
    }

    /**
     * Gets plant
     *
     * @return string
     */
    public function getPlant()
    {
        return $this->container['plant'];
    }

    /**
     * Sets plant
     *
     * @param string $plant plant
     *
     * @return self
     */
    public function setPlant($plant)
    {
        if (is_null($plant)) {
            throw new \InvalidArgumentException('non-nullable plant cannot be null');
        }
        if ((mb_strlen($plant) > 4)) {
            throw new \InvalidArgumentException('invalid length for $plant when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 4.');
        }

        $this->container['plant'] = $plant;

        return $this;
    }

    /**
     * Gets storage_location
     *
     * @return string
     */
    public function getStorageLocation()
    {
        return $this->container['storage_location'];
    }

    /**
     * Sets storage_location
     *
     * @param string $storage_location storage_location
     *
     * @return self
     */
    public function setStorageLocation($storage_location)
    {
        if (is_null($storage_location)) {
            throw new \InvalidArgumentException('non-nullable storage_location cannot be null');
        }
        if ((mb_strlen($storage_location) > 4)) {
            throw new \InvalidArgumentException('invalid length for $storage_location when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 4.');
        }

        $this->container['storage_location'] = $storage_location;

        return $this;
    }

    /**
     * Gets batch
     *
     * @return string
     */
    public function getBatch()
    {
        return $this->container['batch'];
    }

    /**
     * Sets batch
     *
     * @param string $batch Batch Number (Stock Identifier)
     *
     * @return self
     */
    public function setBatch($batch)
    {
        if (is_null($batch)) {
            throw new \InvalidArgumentException('non-nullable batch cannot be null');
        }
        if ((mb_strlen($batch) > 10)) {
            throw new \InvalidArgumentException('invalid length for $batch when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 10.');
        }

        $this->container['batch'] = $batch;

        return $this;
    }

    /**
     * Gets supplier
     *
     * @return string
     */
    public function getSupplier()
    {
        return $this->container['supplier'];
    }

    /**
     * Sets supplier
     *
     * @param string $supplier Supplier for Special Stock
     *
     * @return self
     */
    public function setSupplier($supplier)
    {
        if (is_null($supplier)) {
            throw new \InvalidArgumentException('non-nullable supplier cannot be null');
        }
        if ((mb_strlen($supplier) > 10)) {
            throw new \InvalidArgumentException('invalid length for $supplier when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 10.');
        }

        $this->container['supplier'] = $supplier;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return string
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param string $customer Customer for Special Stock
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        if ((mb_strlen($customer) > 10)) {
            throw new \InvalidArgumentException('invalid length for $customer when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 10.');
        }

        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets wbs_element_internal_id
     *
     * @return string
     */
    public function getWbsElementInternalId()
    {
        return $this->container['wbs_element_internal_id'];
    }

    /**
     * Sets wbs_element_internal_id
     *
     * @param string $wbs_element_internal_id WBS Element
     *
     * @return self
     */
    public function setWbsElementInternalId($wbs_element_internal_id)
    {
        if (is_null($wbs_element_internal_id)) {
            throw new \InvalidArgumentException('non-nullable wbs_element_internal_id cannot be null');
        }
        if ((mb_strlen($wbs_element_internal_id) > 8)) {
            throw new \InvalidArgumentException('invalid length for $wbs_element_internal_id when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 8.');
        }

        $this->container['wbs_element_internal_id'] = $wbs_element_internal_id;

        return $this;
    }

    /**
     * Gets sd_document
     *
     * @return string
     */
    public function getSdDocument()
    {
        return $this->container['sd_document'];
    }

    /**
     * Sets sd_document
     *
     * @param string $sd_document Sales order number of valuated sales order stock
     *
     * @return self
     */
    public function setSdDocument($sd_document)
    {
        if (is_null($sd_document)) {
            throw new \InvalidArgumentException('non-nullable sd_document cannot be null');
        }
        if ((mb_strlen($sd_document) > 10)) {
            throw new \InvalidArgumentException('invalid length for $sd_document when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 10.');
        }

        $this->container['sd_document'] = $sd_document;

        return $this;
    }

    /**
     * Gets sd_document_item
     *
     * @return string
     */
    public function getSdDocumentItem()
    {
        return $this->container['sd_document_item'];
    }

    /**
     * Sets sd_document_item
     *
     * @param string $sd_document_item Sales Order Item of Valuated Sales Order Stock
     *
     * @return self
     */
    public function setSdDocumentItem($sd_document_item)
    {
        if (is_null($sd_document_item)) {
            throw new \InvalidArgumentException('non-nullable sd_document_item cannot be null');
        }
        if ((mb_strlen($sd_document_item) > 6)) {
            throw new \InvalidArgumentException('invalid length for $sd_document_item when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 6.');
        }

        $this->container['sd_document_item'] = $sd_document_item;

        return $this;
    }

    /**
     * Gets inventory_special_stock_type
     *
     * @return string
     */
    public function getInventorySpecialStockType()
    {
        return $this->container['inventory_special_stock_type'];
    }

    /**
     * Sets inventory_special_stock_type
     *
     * @param string $inventory_special_stock_type inventory_special_stock_type
     *
     * @return self
     */
    public function setInventorySpecialStockType($inventory_special_stock_type)
    {
        if (is_null($inventory_special_stock_type)) {
            throw new \InvalidArgumentException('non-nullable inventory_special_stock_type cannot be null');
        }
        if ((mb_strlen($inventory_special_stock_type) > 1)) {
            throw new \InvalidArgumentException('invalid length for $inventory_special_stock_type when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 1.');
        }

        $this->container['inventory_special_stock_type'] = $inventory_special_stock_type;

        return $this;
    }

    /**
     * Gets inventory_stock_type
     *
     * @return string
     */
    public function getInventoryStockType()
    {
        return $this->container['inventory_stock_type'];
    }

    /**
     * Sets inventory_stock_type
     *
     * @param string $inventory_stock_type Stock Type of Goods Movement (Stock Identifier)
     *
     * @return self
     */
    public function setInventoryStockType($inventory_stock_type)
    {
        if (is_null($inventory_stock_type)) {
            throw new \InvalidArgumentException('non-nullable inventory_stock_type cannot be null');
        }
        if ((mb_strlen($inventory_stock_type) > 2)) {
            throw new \InvalidArgumentException('invalid length for $inventory_stock_type when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 2.');
        }

        $this->container['inventory_stock_type'] = $inventory_stock_type;

        return $this;
    }

    /**
     * Gets wbs_element_external_id
     *
     * @return string|null
     */
    public function getWbsElementExternalId()
    {
        return $this->container['wbs_element_external_id'];
    }

    /**
     * Sets wbs_element_external_id
     *
     * @param string|null $wbs_element_external_id Work Breakdown Structure Element (WBS Element) Edited
     *
     * @return self
     */
    public function setWbsElementExternalId($wbs_element_external_id)
    {
        if (is_null($wbs_element_external_id)) {
            array_push($this->openAPINullablesSetToNull, 'wbs_element_external_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('wbs_element_external_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($wbs_element_external_id) && (mb_strlen($wbs_element_external_id) > 24)) {
            throw new \InvalidArgumentException('invalid length for $wbs_element_external_id when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 24.');
        }

        $this->container['wbs_element_external_id'] = $wbs_element_external_id;

        return $this;
    }

    /**
     * Gets material_base_unit
     *
     * @return string|null
     */
    public function getMaterialBaseUnit()
    {
        return $this->container['material_base_unit'];
    }

    /**
     * Sets material_base_unit
     *
     * @param string|null $material_base_unit material_base_unit
     *
     * @return self
     */
    public function setMaterialBaseUnit($material_base_unit)
    {
        if (is_null($material_base_unit)) {
            array_push($this->openAPINullablesSetToNull, 'material_base_unit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('material_base_unit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($material_base_unit) && (mb_strlen($material_base_unit) > 3)) {
            throw new \InvalidArgumentException('invalid length for $material_base_unit when calling APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreate., must be smaller than or equal to 3.');
        }

        $this->container['material_base_unit'] = $material_base_unit;

        return $this;
    }

    /**
     * Gets matl_wrhs_stk_qty_in_matl_base_unit
     *
     * @return float|null
     */
    public function getMatlWrhsStkQtyInMatlBaseUnit()
    {
        return $this->container['matl_wrhs_stk_qty_in_matl_base_unit'];
    }

    /**
     * Sets matl_wrhs_stk_qty_in_matl_base_unit
     *
     * @param float|null $matl_wrhs_stk_qty_in_matl_base_unit matl_wrhs_stk_qty_in_matl_base_unit
     *
     * @return self
     */
    public function setMatlWrhsStkQtyInMatlBaseUnit($matl_wrhs_stk_qty_in_matl_base_unit)
    {
        if (is_null($matl_wrhs_stk_qty_in_matl_base_unit)) {
            array_push($this->openAPINullablesSetToNull, 'matl_wrhs_stk_qty_in_matl_base_unit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('matl_wrhs_stk_qty_in_matl_base_unit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }


        $this->container['matl_wrhs_stk_qty_in_matl_base_unit'] = $matl_wrhs_stk_qty_in_matl_base_unit;

        return $this;
    }

    /**
     * Gets to_material_serial_number
     *
     * @return \BeLenka\SAP\MaterialStock\Model\APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreateToMaterialSerialNumber|null
     */
    public function getToMaterialSerialNumber()
    {
        return $this->container['to_material_serial_number'];
    }

    /**
     * Sets to_material_serial_number
     *
     * @param \BeLenka\SAP\MaterialStock\Model\APIMATERIALSTOCKSRVAMatlStkInAcctModTypeCreateToMaterialSerialNumber|null $to_material_serial_number to_material_serial_number
     *
     * @return self
     */
    public function setToMaterialSerialNumber($to_material_serial_number)
    {
        if (is_null($to_material_serial_number)) {
            throw new \InvalidArgumentException('non-nullable to_material_serial_number cannot be null');
        }
        $this->container['to_material_serial_number'] = $to_material_serial_number;

        return $this;
    }

    /**
     * Gets to_material_stock
     *
     * @return \BeLenka\SAP\MaterialStock\Model\APIMATERIALSTOCKSRVAMaterialStockTypeCreate|null
     */
    public function getToMaterialStock()
    {
        return $this->container['to_material_stock'];
    }

    /**
     * Sets to_material_stock
     *
     * @param \BeLenka\SAP\MaterialStock\Model\APIMATERIALSTOCKSRVAMaterialStockTypeCreate|null $to_material_stock to_material_stock
     *
     * @return self
     */
    public function setToMaterialStock($to_material_stock)
    {
        if (is_null($to_material_stock)) {
            throw new \InvalidArgumentException('non-nullable to_material_stock cannot be null');
        }
        $this->container['to_material_stock'] = $to_material_stock;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


