<?php
/**
 * BatchRequestsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\MaterialStock
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Material Stock - Read
 *
 * This service enables you to retrieve material stock information using the OData protocol with filter data provided in the payload. It can be consumed by external warehouse applications.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\MaterialStock\Test\Api;

use \BeLenka\SAP\MaterialStock\Configuration;
use \BeLenka\SAP\MaterialStock\ApiException;
use \BeLenka\SAP\MaterialStock\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BatchRequestsApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\MaterialStock
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BatchRequestsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for batchPost
     *
     * Send a group of requests.
     *
     */
    public function testBatchPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
